Implementation;Place and Route;RootName:top_level
Implementation;Place and Route||(null)||Please refer to the log file for details about 6 Info(s)||top_level_layout_log.log;liberoaction://open_report/file/top_level_layout_log.log||(null);(null)
Implementation;Generate Bitstream;RootName:top_level
Implementation;Generate Bitstream||(null)||Please refer to the log file for details about 1 Info(s)||top_level_generateBitstream.log;liberoaction://open_report/file/top_level_generateBitstream.log||(null);(null)
HelpInfo,/usr/local/microchip/Libero_SoC_v2022.2/SynplifyPro/lib/html,fpgahelp.qhc,synerrmsg.mp,/usr/local/microchip/Libero_SoC_v2022.2/SynplifyPro/bin/assistant
